#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/00_dokku-standard/functions"

exec_app_json_scripts() {
  declare desc="core app.json scripts execution"
  local trigger="$0 app_json_scripts"
  local APP="$1"

  case "$0" in
    *pre-deploy)
      local IMAGE_TAG="$2"
      local IMAGE=$(get_app_image_name "$APP" "$IMAGE_TAG")
      local PHASE_SCRIPT_KEY="dokku.predeploy"
      ;;
    *post-deploy)
      local IMAGE_TAG="$4"
      local IMAGE=$(get_app_image_name "$APP" "$IMAGE_TAG")
      local PHASE_SCRIPT_KEY="dokku.postdeploy"
      ;;
  esac

  dokku_log_info1 "Attempting to run scripts.$PHASE_SCRIPT_KEY from app.json (if defined)"
  execute_script "$APP" "$IMAGE" "$PHASE_SCRIPT_KEY"
}

exec_app_json_scripts "$@"
