#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/00_dokku-standard/functions"

exec_app_json_scripts_post_initial_deploy() {
  declare desc="core app.json scripts execution (heroku postdeploy)"
  local trigger="$0 app_json_scripts_post_initial_deploy"
  local APP="$1"
  local IMAGE=$(get_app_image_name "$APP")
  local PHASE_SCRIPT_KEY="postdeploy"

  dokku_log_info1 "Attempting to run scripts.$PHASE_SCRIPT_KEY from app.json (if defined)"
  execute_script "$APP" "$IMAGE" "$PHASE_SCRIPT_KEY"
}

exec_app_json_scripts "$@"
